SET SERVEROUTPUT ON;

DECLARE

IDADE NUMBER;
NOME VARCHAR2 (30) := 'JONAS';
ENDERECO VARCHAR2(50) := '&DIGITE_ENERECO';

BEGIN 
IDADE := 39;
DBMS_OUTPUT.PUT_LINE('A IDADE INFORMADA É: ' ||IDADE);
DBMS_OUTPUT.PUT_LINE('O NOME INFORMADO É: ' ||NOME);
DBMS_OUTPUT.PUT_LINE('O SEU ENDEREÇO É: ' ||ENDERECO);

END;

SET SERVEROUTPUT ON; 

DECLARE

SALARIO NUMBER := 1500;

BEGIN

DBMS_OUTPUT.PUT_LINE('O SALÁRIO COM ACRESCIMO DE 25% É: r$' ||SALARIO * 1.25);

END;

SET SERVEROUTPUT ON;

DECLARE

VALOR_DOLAR NUMBER := 45;

BEGIN

DBMS_OUTPUT.PUT_LINE('O VALOR EM REAIS EQUIVALE A R$: ' ||VALOR_DOLAR * 5.75);

END;


SET SERVEROUTPUT ON;

DECLARE

valor_carro NUMBER := &valor;



BEGIN

DBMS_OUTPUT.PUT_LINE('O VALOR TOTAL SEM JUROS É: R$' ||valor_carro);
DBMS_OUTPUT.PUT_LINE('O VALOR PARCELA DIVIDO EM 6 VEZZES É DE: R$ ' ||ROUND(valor_carro/1.20/5 * 1.10));
DBMS_OUTPUT.PUT_LINE('O VALOR PARCELA DIVIDO EM 12 VEZES É DE: R$ ' ||ROUND(valor_carro/1.20/11 * 1.15));
DBMS_OUTPUT.PUT_LINE('O VALOR PARCELA DIVIDO EM 18 VEZES É DE: R$ ' ||ROUND(valor_carro/1.20/17 * 1.20));
DBMS_OUTPUT.PUT_LINE('O VALOR PARCELA DIVIDO EM 6 VEZZES É DE: R$ ' ||ROUND(valor_carro/1.20 * 1.10));
DBMS_OUTPUT.PUT_LINE('O VALOR PARCELA DIVIDO EM 12 VEZES É DE: R$ ' ||ROUND(valor_carro/1.20 * 1.15));
DBMS_OUTPUT.PUT_LINE('O VALOR PARCELA DIVIDO EM 18 VEZES É DE: R$ ' ||ROUND(valor_carro/1.20 * 1.20));

END;

